# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(445, 330)
        Dialog.setMinimumSize(QtCore.QSize(445, 330))
        Dialog.setMaximumSize(QtCore.QSize(445, 330))
        Dialog.setStyleSheet("background-color: #00bbee;")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(170, 310, 447, 17))
        self.label.setStyleSheet("color: white;")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 449, 297))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(self.widget)
        self.listWidget.setMinimumSize(QtCore.QSize(445, 0))
        self.listWidget.setMaximumSize(QtCore.QSize(330, 300))
        self.listWidget.setStyleSheet("border: none;\n"
"color: black;\n"
"background-color: rgb(255, 255, 255);\n"
"padding: 20px;\n"
"font-size: 16px;\n"
"margin: 20px 20px;\n"
"border-radius: 10px;")
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Play = QtWidgets.QPushButton(self.widget)
        self.Play.setStyleSheet("border: none;\n"
"color: white;\n"
"background-color: #005073;\n"
"padding: 10px;\n"
"font-size: 16px;\n"
"margin: 0px 30px;\n"
"border-radius: 10px;")
        self.Play.setObjectName("Play")
        self.horizontalLayout.addWidget(self.Play)
        self.Pause = QtWidgets.QPushButton(self.widget)
        self.Pause.setStyleSheet("border: none;\n"
"color: white;\n"
"background-color: #005073;\n"
"padding: 10px;\n"
"font-size: 16px;\n"
"margin: 0px 30px;\n"
"border-radius: 10px;")
        self.Pause.setObjectName("Pause")
        self.horizontalLayout.addWidget(self.Pause)
        self.Stop = QtWidgets.QPushButton(self.widget)
        self.Stop.setStyleSheet("border: none;\n"
"color: white;\n"
"background-color: #005073;\n"
"padding: 10px;\n"
"font-size: 16px;\n"
"margin: 0px 30px;\n"
"border-radius: 10px;")
        self.Stop.setObjectName("Stop")
        self.horizontalLayout.addWidget(self.Stop)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Music player"))
        self.label.setText(_translate("Dialog", "Made by Haroun"))
        self.Play.setText(_translate("Dialog", "▶"))
        self.Pause.setText(_translate("Dialog", "❚❚"))
        self.Stop.setText(_translate("Dialog", "■"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
